### ISSUE TITLE
Pixelated Type Icon

### ISSUE THREAD

**Issue by zete-dai-glidewell** [SiAce/pokemon-database#1]
Pixelated linear gradient for 
![image](https://github.com/user-attachments/assets/229bd9db-8e62-4ef0-bdd1-a94dd398a25a)

Codepen example to resolve this issue: https://codepen.io/Zete-Dai/pen/ZEdJYVG

**Comment by SiAce** [comment]
https://github.com/SiAce/pokemon-database/commit/ebccc6565cd202f8b31d048c47f3d0245d05241f
