### ISSUE TITLE
Abbreviation Error for Some Versions

### ISSUE THREAD

**Issue by zete-dai-glidewell** [SiAce/pokemon-database#2]
![Screenshot 2024-08-07 102146](https://github.com/user-attachments/assets/f0011c91-8c8b-4da9-a356-759c23c98830)

See this post: https://stackoverflow.com/questions/7888238/javascript-split-string-on-uppercase-characters

**Comment by SiAce** [comment]
https://github.com/SiAce/pokemon-database/commit/ebccc6565cd202f8b31d048c47f3d0245d05241f
