### ISSUE TITLE
Add conditions for evolution chain

### ISSUE THREAD

**Issue by SiAce** [SiAce/pokemon-database#6]

**Comment by zete-dai-glidewell** [comment]
https://github.com/SiAce/pokemon-database/blob/v5/data/csv/pokemon_evolution.csv

**Comment by zete-dai-glidewell** [comment]
[evolution-detail.patch](https://github.com/user-attachments/files/17156923/evolution-detail.patch)

**Comment by SiAce** [comment]
https://github.com/SiAce/pokemon-database/commit/cb25e5da27f70e63138266203ad729b3a235a30d
